database:
  database: web3_idp_dev
  url: localhost
  port: 54321
  username: postgres
  password: pw
  migrate: true
settings:
  loglevel: 1
  url: 0.0.0.0:4000
hydra:
  adminURL: http://localhost:4445
