// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/OdysseyMomentumExperience/web3-identity-provider/ent/schema"
	"github.com/OdysseyMomentumExperience/web3-identity-provider/ent/web3challenge"
	"github.com/OdysseyMomentumExperience/web3-identity-provider/ent/web3user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	web3challengeFields := schema.Web3Challenge{}.Fields()
	_ = web3challengeFields
	// web3challengeDescUUID is the schema descriptor for uuid field.
	web3challengeDescUUID := web3challengeFields[0].Descriptor()
	// web3challenge.DefaultUUID holds the default value on creation for the uuid field.
	web3challenge.DefaultUUID = web3challengeDescUUID.Default.(func() uuid.UUID)
	web3userFields := schema.Web3User{}.Fields()
	_ = web3userFields
	// web3userDescUUID is the schema descriptor for uuid field.
	web3userDescUUID := web3userFields[0].Descriptor()
	// web3user.DefaultUUID holds the default value on creation for the uuid field.
	web3user.DefaultUUID = web3userDescUUID.Default.(func() uuid.UUID)
}
