// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/OdysseyMomentumExperience/web3-identity-provider/ent/predicate"
	"github.com/OdysseyMomentumExperience/web3-identity-provider/ent/web3challenge"
	"github.com/OdysseyMomentumExperience/web3-identity-provider/ent/web3user"
	"github.com/google/uuid"
)

// Web3UserUpdate is the builder for updating Web3User entities.
type Web3UserUpdate struct {
	config
	hooks    []Hook
	mutation *Web3UserMutation
}

// Where appends a list predicates to the Web3UserUpdate builder.
func (wu *Web3UserUpdate) Where(ps ...predicate.Web3User) *Web3UserUpdate {
	wu.mutation.Where(ps...)
	return wu
}

// SetUUID sets the "uuid" field.
func (wu *Web3UserUpdate) SetUUID(u uuid.UUID) *Web3UserUpdate {
	wu.mutation.SetUUID(u)
	return wu
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (wu *Web3UserUpdate) SetNillableUUID(u *uuid.UUID) *Web3UserUpdate {
	if u != nil {
		wu.SetUUID(*u)
	}
	return wu
}

// SetAddress sets the "address" field.
func (wu *Web3UserUpdate) SetAddress(s string) *Web3UserUpdate {
	wu.mutation.SetAddress(s)
	return wu
}

// SetWalletType sets the "wallet_type" field.
func (wu *Web3UserUpdate) SetWalletType(wt web3user.WalletType) *Web3UserUpdate {
	wu.mutation.SetWalletType(wt)
	return wu
}

// SetNillableWalletType sets the "wallet_type" field if the given value is not nil.
func (wu *Web3UserUpdate) SetNillableWalletType(wt *web3user.WalletType) *Web3UserUpdate {
	if wt != nil {
		wu.SetWalletType(*wt)
	}
	return wu
}

// ClearWalletType clears the value of the "wallet_type" field.
func (wu *Web3UserUpdate) ClearWalletType() *Web3UserUpdate {
	wu.mutation.ClearWalletType()
	return wu
}

// AddWeb3ChallengeIDs adds the "web3_challenges" edge to the Web3Challenge entity by IDs.
func (wu *Web3UserUpdate) AddWeb3ChallengeIDs(ids ...int) *Web3UserUpdate {
	wu.mutation.AddWeb3ChallengeIDs(ids...)
	return wu
}

// AddWeb3Challenges adds the "web3_challenges" edges to the Web3Challenge entity.
func (wu *Web3UserUpdate) AddWeb3Challenges(w ...*Web3Challenge) *Web3UserUpdate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wu.AddWeb3ChallengeIDs(ids...)
}

// Mutation returns the Web3UserMutation object of the builder.
func (wu *Web3UserUpdate) Mutation() *Web3UserMutation {
	return wu.mutation
}

// ClearWeb3Challenges clears all "web3_challenges" edges to the Web3Challenge entity.
func (wu *Web3UserUpdate) ClearWeb3Challenges() *Web3UserUpdate {
	wu.mutation.ClearWeb3Challenges()
	return wu
}

// RemoveWeb3ChallengeIDs removes the "web3_challenges" edge to Web3Challenge entities by IDs.
func (wu *Web3UserUpdate) RemoveWeb3ChallengeIDs(ids ...int) *Web3UserUpdate {
	wu.mutation.RemoveWeb3ChallengeIDs(ids...)
	return wu
}

// RemoveWeb3Challenges removes "web3_challenges" edges to Web3Challenge entities.
func (wu *Web3UserUpdate) RemoveWeb3Challenges(w ...*Web3Challenge) *Web3UserUpdate {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wu.RemoveWeb3ChallengeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wu *Web3UserUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(wu.hooks) == 0 {
		if err = wu.check(); err != nil {
			return 0, err
		}
		affected, err = wu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*Web3UserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = wu.check(); err != nil {
				return 0, err
			}
			wu.mutation = mutation
			affected, err = wu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(wu.hooks) - 1; i >= 0; i-- {
			if wu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = wu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (wu *Web3UserUpdate) SaveX(ctx context.Context) int {
	affected, err := wu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wu *Web3UserUpdate) Exec(ctx context.Context) error {
	_, err := wu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wu *Web3UserUpdate) ExecX(ctx context.Context) {
	if err := wu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wu *Web3UserUpdate) check() error {
	if v, ok := wu.mutation.WalletType(); ok {
		if err := web3user.WalletTypeValidator(v); err != nil {
			return &ValidationError{Name: "wallet_type", err: fmt.Errorf(`ent: validator failed for field "Web3User.wallet_type": %w`, err)}
		}
	}
	return nil
}

func (wu *Web3UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   web3user.Table,
			Columns: web3user.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: web3user.FieldID,
			},
		},
	}
	if ps := wu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wu.mutation.UUID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: web3user.FieldUUID,
		})
	}
	if value, ok := wu.mutation.Address(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: web3user.FieldAddress,
		})
	}
	if value, ok := wu.mutation.WalletType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: web3user.FieldWalletType,
		})
	}
	if wu.mutation.WalletTypeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Column: web3user.FieldWalletType,
		})
	}
	if wu.mutation.Web3ChallengesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   web3user.Web3ChallengesTable,
			Columns: []string{web3user.Web3ChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: web3challenge.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.RemovedWeb3ChallengesIDs(); len(nodes) > 0 && !wu.mutation.Web3ChallengesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   web3user.Web3ChallengesTable,
			Columns: []string{web3user.Web3ChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: web3challenge.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wu.mutation.Web3ChallengesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   web3user.Web3ChallengesTable,
			Columns: []string{web3user.Web3ChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: web3challenge.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{web3user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// Web3UserUpdateOne is the builder for updating a single Web3User entity.
type Web3UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Web3UserMutation
}

// SetUUID sets the "uuid" field.
func (wuo *Web3UserUpdateOne) SetUUID(u uuid.UUID) *Web3UserUpdateOne {
	wuo.mutation.SetUUID(u)
	return wuo
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (wuo *Web3UserUpdateOne) SetNillableUUID(u *uuid.UUID) *Web3UserUpdateOne {
	if u != nil {
		wuo.SetUUID(*u)
	}
	return wuo
}

// SetAddress sets the "address" field.
func (wuo *Web3UserUpdateOne) SetAddress(s string) *Web3UserUpdateOne {
	wuo.mutation.SetAddress(s)
	return wuo
}

// SetWalletType sets the "wallet_type" field.
func (wuo *Web3UserUpdateOne) SetWalletType(wt web3user.WalletType) *Web3UserUpdateOne {
	wuo.mutation.SetWalletType(wt)
	return wuo
}

// SetNillableWalletType sets the "wallet_type" field if the given value is not nil.
func (wuo *Web3UserUpdateOne) SetNillableWalletType(wt *web3user.WalletType) *Web3UserUpdateOne {
	if wt != nil {
		wuo.SetWalletType(*wt)
	}
	return wuo
}

// ClearWalletType clears the value of the "wallet_type" field.
func (wuo *Web3UserUpdateOne) ClearWalletType() *Web3UserUpdateOne {
	wuo.mutation.ClearWalletType()
	return wuo
}

// AddWeb3ChallengeIDs adds the "web3_challenges" edge to the Web3Challenge entity by IDs.
func (wuo *Web3UserUpdateOne) AddWeb3ChallengeIDs(ids ...int) *Web3UserUpdateOne {
	wuo.mutation.AddWeb3ChallengeIDs(ids...)
	return wuo
}

// AddWeb3Challenges adds the "web3_challenges" edges to the Web3Challenge entity.
func (wuo *Web3UserUpdateOne) AddWeb3Challenges(w ...*Web3Challenge) *Web3UserUpdateOne {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wuo.AddWeb3ChallengeIDs(ids...)
}

// Mutation returns the Web3UserMutation object of the builder.
func (wuo *Web3UserUpdateOne) Mutation() *Web3UserMutation {
	return wuo.mutation
}

// ClearWeb3Challenges clears all "web3_challenges" edges to the Web3Challenge entity.
func (wuo *Web3UserUpdateOne) ClearWeb3Challenges() *Web3UserUpdateOne {
	wuo.mutation.ClearWeb3Challenges()
	return wuo
}

// RemoveWeb3ChallengeIDs removes the "web3_challenges" edge to Web3Challenge entities by IDs.
func (wuo *Web3UserUpdateOne) RemoveWeb3ChallengeIDs(ids ...int) *Web3UserUpdateOne {
	wuo.mutation.RemoveWeb3ChallengeIDs(ids...)
	return wuo
}

// RemoveWeb3Challenges removes "web3_challenges" edges to Web3Challenge entities.
func (wuo *Web3UserUpdateOne) RemoveWeb3Challenges(w ...*Web3Challenge) *Web3UserUpdateOne {
	ids := make([]int, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wuo.RemoveWeb3ChallengeIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wuo *Web3UserUpdateOne) Select(field string, fields ...string) *Web3UserUpdateOne {
	wuo.fields = append([]string{field}, fields...)
	return wuo
}

// Save executes the query and returns the updated Web3User entity.
func (wuo *Web3UserUpdateOne) Save(ctx context.Context) (*Web3User, error) {
	var (
		err  error
		node *Web3User
	)
	if len(wuo.hooks) == 0 {
		if err = wuo.check(); err != nil {
			return nil, err
		}
		node, err = wuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*Web3UserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = wuo.check(); err != nil {
				return nil, err
			}
			wuo.mutation = mutation
			node, err = wuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(wuo.hooks) - 1; i >= 0; i-- {
			if wuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = wuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, wuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (wuo *Web3UserUpdateOne) SaveX(ctx context.Context) *Web3User {
	node, err := wuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wuo *Web3UserUpdateOne) Exec(ctx context.Context) error {
	_, err := wuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wuo *Web3UserUpdateOne) ExecX(ctx context.Context) {
	if err := wuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wuo *Web3UserUpdateOne) check() error {
	if v, ok := wuo.mutation.WalletType(); ok {
		if err := web3user.WalletTypeValidator(v); err != nil {
			return &ValidationError{Name: "wallet_type", err: fmt.Errorf(`ent: validator failed for field "Web3User.wallet_type": %w`, err)}
		}
	}
	return nil
}

func (wuo *Web3UserUpdateOne) sqlSave(ctx context.Context) (_node *Web3User, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   web3user.Table,
			Columns: web3user.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: web3user.FieldID,
			},
		},
	}
	id, ok := wuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Web3User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, web3user.FieldID)
		for _, f := range fields {
			if !web3user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != web3user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wuo.mutation.UUID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: web3user.FieldUUID,
		})
	}
	if value, ok := wuo.mutation.Address(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: web3user.FieldAddress,
		})
	}
	if value, ok := wuo.mutation.WalletType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: web3user.FieldWalletType,
		})
	}
	if wuo.mutation.WalletTypeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Column: web3user.FieldWalletType,
		})
	}
	if wuo.mutation.Web3ChallengesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   web3user.Web3ChallengesTable,
			Columns: []string{web3user.Web3ChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: web3challenge.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.RemovedWeb3ChallengesIDs(); len(nodes) > 0 && !wuo.mutation.Web3ChallengesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   web3user.Web3ChallengesTable,
			Columns: []string{web3user.Web3ChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: web3challenge.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wuo.mutation.Web3ChallengesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   web3user.Web3ChallengesTable,
			Columns: []string{web3user.Web3ChallengesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: web3challenge.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Web3User{config: wuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{web3user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
