// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Web3Challenge is the predicate function for web3challenge builders.
type Web3Challenge func(*sql.Selector)

// Web3User is the predicate function for web3user builders.
type Web3User func(*sql.Selector)
